/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SHOLLYP } from './SHOLLYP.js';
export * as factories from './factories/index.js';
export { SHOLLYP__factory } from './factories/SHOLLYP__factory.js';